### ISSUE TITLE
Missing break in stm32u0xx_ll_rcc.c LL_RCC_GetADCClockFreq() case LL_RCC_ADC_CLKSOURCE_PLLP:

### ISSUE THREAD

**Issue by CanastraRF** [STMicroelectronics/stm32u0xx-hal-driver#1]
Hi 
my compiler report a missing break in Funktion LL_RCC_GetADCClockFreq() for case  LL_RCC_ADC_CLKSOURCE_PLLP:
Please fix this
Please enable most warning in your tool chain. Modern tools report this.

**Comment by ALABSTM** [comment]
ST Internal Reference: 182916

**Comment by ALABSTM** [comment]
Hi @CanastraRF,

You're absolutely right about this missing `break` instruction. Issue forwarded to our development teams.

With regards,

**Comment by TOUNSTM** [comment]
Fixed in f949e9dd4d8509051e0e4fd34067a3cfc37fe089
